name: 

on:
  push:
    branches: []
  pull_request:
    branches: []

jobs:
  build-windows:
    runs-on: 
    steps:
      - uses: 
      - name: 
        uses: 
        with:
          python-version: '3.11'
      - name: 
        run: 
      - name: 
        run: 
      - name: 
        uses: 
        with:
          name: 
          path: 

  build-macos:
    runs-on: 
    steps:
      - uses: 
      - name: 
        uses: 
        with:
          python-version: '3.11'
      - name: 
        run: 
      - name: 
        run: 
      - name: 
        uses: 
        with:
          name: 
          path: 
